services:
  rms:
    build: .
    container_name: raspberry-media-server
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - "PUID=${PUID:-1000}"
      - "PGID=${PGID:-1000}"
      - "TZ=${TZ:-Europe/Madrid}"
    volumes:
      - "${MEDIA_DIR:-./media}:/app/media"
      - "${CONFIG_DIR:-./config}:/app/config"
